Add promise support and update deprecated methods from Dropbox
sallar/dropbox-fs pull request #19
Opened 2021-11-07 21:29 UTC by avidianity

1. This also incorporates #16's fix with tests.
2. Lock files are [removed](https://www.twilio.com/blog/lockfiles-nodejs).
3. Deprecated methods are updated to use the V2 methods.

2021-11-24 11:12 UTC, sallar requested changes
Hey! Thanks for this and sorry it took me this long to check. 
One thing though, can we rename the deprecated methods to use a more explicit name instead of V2? Like `deprecated__moveFile` or something along these lines?

2021-11-24 23:10 UTC, avidianity commented
> Hey! Thanks for this and sorry it took me this long to check. One thing though, can we rename the deprecated methods to use a more explicit name instead of V2? Like `deprecated__moveFile` or something along these lines?

I think you misunderstood. The deprecated methods are from the `dropbox` package, so I updated this package to use `dropbox`'s V2 methods so that there are no deprecated code being used throughout this package.

2021-11-25 12:44 UTC, sallar commented
@avidianity ah sorry it was a long day and my brain wasn't working. thank you.

2021-11-25 12:45 UTC, sallar approved these changes

2021-11-25 12:45 UTC, merged